### ISSUE TITLE
Custom Filter Kanban view doesn't save tasks in buckets

### ISSUE THREAD

**Issue by Sim0nW0lf** [go-vikunja/vikunja#341]
### Description

The feature to have your own Kanban view for Custom filters was implemented in v0.24.0 I believe with this commit https://github.com/go-vikunja/vikunja/commit/359b07dabba79ae5b4f723b673f6332d8ead528f and discussed here: https://community.vikunja.io/t/unable-to-display-the-kanban-board-for-filters-across-multiple-lists/325/17. But since v0.24.3, when I change buckets in the Kanban view of Custom Filters I get this error in the logs and the task will move back to the default bucket.

```
usa_vikunja     | 2024-10-14T12:51:12Z: ERROR   ▶ 1d2d3 Error while handling message e1ed032e-6c85-4e9a-8004-8b4058ea7096, topic_poisoned=task.updated, handler_poisoned=task.updated.task.set.saved.filter.views, subscriber_poisoned=gochannel.GoChannel, reason_poisoned=panic occurred: "invalid memory address or nil pointer dereference", stacktrace: 
usa_vikunja     | goroutine 71847 [running]:
usa_vikunja     | runtime/debug.Stack()
usa_vikunja     |       /go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.linux-amd64/src/runtime/debug/stack.go:26 +0x5e
usa_vikunja     | github.com/ThreeDotsLabs/watermill/message/router/middleware.Recoverer.func1.1()
usa_vikunja     |       /go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/router/middleware/recoverer.go:29 +0x50
usa_vikunja     | panic({0x1681380?, 0x4a107c0?})
usa_vikunja     |       /go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.linux-amd64/src/runtime/panic.go:785 +0x132
usa_vikunja     | github.com/typesense/typesense-go/v2/typesense.GenericCollection[...](...)
usa_vikunja     |       /go/pkg/mod/github.com/typesense/typesense-go/v2@v2.0.0/typesense/client.go:32
usa_vikunja     | github.com/typesense/typesense-go/v2/typesense.(*Client).Collection(...)
usa_vikunja     |       /go/pkg/mod/github.com/typesense/typesense-go/v2@v2.0.0/typesense/client.go:36
usa_vikunja     | code.vikunja.io/api/pkg/models.reindexTasksInTypesense(0xc001596680, 0xc000933ae0)
usa_vikunja     |       /go/src/code.vikunja.io/api/pkg/models/typesense.go:325 +0x42d
usa_vikunja     | code.vikunja.io/api/pkg/models.(*UpdateTaskInSavedFilterViews).Handle(0x3defc18?, 0xc00188bf20)
usa_vikunja     |       /go/src/code.vikunja.io/api/pkg/models/listeners.go:734 +0xefd
usa_vikunja     | github.com/ThreeDotsLabs/watermill/message.(*Router).AddNoPublisherHandler.func1(0xc00028d570?)
usa_vikunja     |       /go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/router.go:338 +0x17
usa_vikunja     | github.com/ThreeDotsLabs/watermill/message/router/middleware.Recoverer.func1(0xc00196fd50?)
usa_vikunja     |       /go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/router/middleware/recoverer.go:33 +0x70
usa_vikunja     | github.com/ThreeDotsLabs/watermill/message/router/middleware.Retry.Middleware-fm.Retry.Middleware.func1(0xc00188bf20)
usa_vikunja     |       /go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/router/middleware/retry.go:72 +0x27e
usa_vikunja     | github.com/ThreeDotsLabs/watermill/message/router/middleware.poisonQueue.Middleware-fm.poisonQueue.Middleware.func1(0x169d9a0?)
usa_vikunja     |       /go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/router/middleware/poison.go:99 +0xa2
usa_vikunja     | github.com/ThreeDotsLabs/watermill/components/metrics.HandlerPrometheusMetricsMiddleware.Middleware-fm.HandlerPrometheusMetricsMiddleware.Middleware.func1(0xc00188bf20)
usa_vikunja     |       /go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/components/metrics/handler.go:58 +0x19b
usa_vikunja     | github.com/ThreeDotsLabs/watermill/message.(*handler).handleMessage(0xc000172680, 0xc00188bf20, 0xc000300168)
usa_vikunja     |       /go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/router.go:783 +0x15b
usa_vikunja     | created by github.com/ThreeDotsLabs/watermill/message.(*handler).run in goroutine 356
usa_vikunja     |       /go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/router.go:628 +0x2a5
usa_vikunja     | ,  payload={"task":{"id":15,"title":"Reise planen","description":"\u003cp\u003eWo, wann?\u003c/p\u003e","done":false,"done_at":"0001-01-01T00:00:00Z","due_date":"0001-01-01T00:00:00Z","reminders":null,"project_id":7,"repeat_after":0,"repeat_mode":0,"priority":1,"start_date":"2024-10-31T23:00:00Z","end_date":"2024-11-12T22:59:00Z","assignees":null,"labels":null,"hex_color":"","percent_done":0,"identifier":"","index":1,"related_tasks":null,"attachments":null,"cover_image_attachment_id":0,"is_favorite":false,"created":"2024-10-07T13:37:11Z","updated":"2024-10-09T14:55:03Z","bucket_id":0,"position":0,"reactions":null,"created_by":null},"doer":{"id":2,"name":"","username":"Myname","email":"myname@mydomain.com","created":"0001-01-01T00:00:00Z","updated":"0001-01-01T00:00:00Z"}}
```

I tested different versions, since the demo site did not have this problem. The demo is running v0.24.1 and since version v0.24.3 this problem exists. When trying v0.24.2 it was still working fine!

### Vikunja Version

v0.24.4

### Browser and version

Chrome

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
The demo is running unstable, built from the latest commit on the `main` branch.

Can you reproduce it with the latest unstable build?

**Comment by Sim0nW0lf** [comment]
When I try the unstable docker tag this is not an issue anymore. It shows Version: v0.24.1-313-3e9c41cfc6, I didn't understand that this is actually the unstable build 👍🏻
