### ISSUE TITLE
Repeating tasks in kanban views should be moved to the default bucket when done

### ISSUE THREAD

**Issue by Ma27** [go-vikunja/vikunja#347]
### Description

So I have a saved filter that contains a bunch of tasks from different projects and has a relatively typical Kanban layout with an "In progress" & "Done" column (amongst others).

Now when moving a repeating task to "In progress" and doing ctrl-click when it's done, it doesn't make much sense to keep it in the `In Progress` column, instead I think it should go back into the default bucket.

I started writing a patch that actually does that, however I still fail to tell the frontend that the bucket has changed (I don't really understand how `BucketID` is set to the correct bucket ID - that one's different depending on which view you're using, right), so perhaps there's a patch ready soonish. Would you be interested in such a patch?

### Vikunja Version

0.24.4

### Can you reproduce the bug on the Vikunja demo site?

Please select

**Comment by Ma27** [comment]
Oh btw speaking of which: does the frontend build work for you currently? I tried to do it in a devenv-shell and it fails like this:

```
❯ Projects/vikunja/frontend main* → pnpm run build

> vikunja-frontend@0.10.0 build /home/ma27/Projects/vikunja/frontend
> vite build && workbox copyLibraries dist/

Building "legacy" build with "@vitejs/plugin-legacy"
plugin-legacy overrode 'build.target'. You should pass 'targets' as an option to this plugin with the list of legacy browsers to support instead.
vite v5.4.10 building for production...
transforming (10) src/router/index.tsnode:events:497
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:161:15)
    at writeGeneric (node:internal/stream_base_commons:152:3)
    at Socket._writeGeneric (node:net:954:11)
    at Socket._write (node:net:966:8)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at AsyncCompiler.writeStdin (/home/ma27/Projects/vikunja/frontend/node_modules/.pnpm/sass-embedded@1.80.6/node_modules/sass-embedded/dist/lib/src/compiler/async.js:30:28)
    at PacketTransformer.writeInboundBuffer (/home/ma27/Projects/vikunja/frontend/node_modules/.pnpm/sass-embedded@1.80.6/node_modules/sass-embedded/dist/lib/src/compiler/async.js:112:18)
    at PacketTransformer.writeInboundProtobuf (/home/ma27/Projects/vikunja/frontend/node_modules/.pnpm/sass-embedded@1.80.6/node_modules/sass-embedded/dist/lib/src/packet-transformer.js:66:18)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v20.17.0
 ELIFECYCLE  Command failed with exit code 1.
```

Can also reproduce this issue when updating the `pkgs.vikunja` derivation from nixpkgs to latest master. I guess I'll try to undo the sass-embedded change temporarily.

**Comment by kolaente** [comment]
Nope, I have the same issue. [Works in CI](https://drone.kolaente.de/vikunja/vikunja/9072/1/27), maybe this is a problem with devenv. Dev watcher seem to work fine though (with `pnpm dev`).

**Comment by Ma27** [comment]
It's not devenv-related, but a problem you'll always have with Nix:

```
[ma27@snens:~/Projects/vikunja/frontend]$ /home/ma27/Projects/vikunja/frontend/node_modules/.pnpm/sass-embedded-linux-x64@1.80.6/node_modules/sass-embedded-linux-x64/dart-sass/src/dart
Could not start dynamically linked executable: /home/ma27/Projects/vikunja/frontend/node_modules/.pnpm/sass-embedded-linux-x64@1.80.6/node_modules/sass-embedded-linux-x64/dart-sass/src/dart
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```

`strace` ftw, the error message didn't really help.

**Comment by kolaente** [comment]
Huh I thought this was statically linked

**Comment by Ma27** [comment]
Btw I fixed it like this in the Nix expression for vikunja, feel free to copy when the next release comes and the package in nixpkgs requires an update:

```diff
diff --git a/pkgs/by-name/vi/vikunja/package.nix b/pkgs/by-name/vi/vikunja/package.nix
index 150b1abc8fb9..3848fad1d06f 100644
--- a/pkgs/by-name/vi/vikunja/package.nix
+++ b/pkgs/by-name/vi/vikunja/package.nix
@@ -28,6 +28,7 @@ let
     doCheck = true;
 
     postBuild = ''
+      find node_modules/.pnpm/sass-embedded-linux-x64@1.80.6/node_modules/sass-embedded-linux-x64/dart-sass/src -name dart -print0 | xargs -I {} -0 patchelf --set-interpreter "$(<$NIX_CC/nix-support/dynamic-linker)" {}
       pnpm run build
     '';
 

```

**Comment by Ma27** [comment]
First iteration available as PR in gitea: https://kolaente.dev/vikunja/vikunja/pulls/2841
Still needs some polishing, but I'd like to get some feedback first.

**Comment by solarmaster961** [comment]
@Ma27 re: "I don't really understand how `BucketID` is set to the correct bucket... that one's
different depending on which view you're using, right" — yes, exactly. Sharing what we found
while digging through this area, in case it helps the patch:

There's no global bucket per task anymore. Bucket membership is **per view**, stored in the
`task_buckets` table (`task_id`, `bucket_id`, `project_view_id`) with a unique index on
(`task_id`, `project_view_id`). The old `bucket_id` column on `tasks` was removed (migration
`20240315110428`). `Task.BucketID` is now a transient field (`xorm:"-"`) populated only
relative to the specific view you're loading, in `GetTasksInBucketsForView`
(`pkg/models/kanban.go`). That's why it differs per view.

For done/default moves, the existing logic is `moveTaskToDoneBuckets` /
`moveTaskToDefaultBuckets` in `pkg/models/tasks.go` — but note they iterate the **task's own
project** views (guarded by `t.ProjectID == ot.ProjectID`). A saved filter is a separate
pseudo-project (`project_id = filterId*-1-1`) with its own Kanban view, so its `task_buckets`
rows are not touched by those functions; they're maintained separately by `addTaskToFilter`
(called from the `UpdateTaskInSavedFilterViews` listener and the
`RegisterAddTaskToFilterViewCron` cron), which currently always inserts into the view's
`DefaultBucketID`.

So to send a repeating task back to the default bucket **in a saved filter's Kanban view**
specifically, you'd update the `task_buckets` row for that view's `project_view_id` (set
`bucket_id` to that view's `DefaultBucketID`), similar to what `addTaskToFilter` /
`updateTaskBucket` already do. On the frontend, the kanban store loads buckets per the active
view, and the per-view `Task.BucketID` comes from that same view-scoped query — so the move has
to target the right `project_view_id` to show up. (Line numbers drift across versions; these
are the function names in current code.)

Slightly related: we're looking at making saved-filter Kanban boards optionally mirror the
source project's bucket — separate topic, we'll raise it on its own so we don't derail this
thread.
