### ISSUE TITLE
OIDC: go panic error when trying to configure a provider

### ISSUE THREAD

**Issue by maiatoja152** [go-vikunja/vikunja#371]
### Description

Other than this issue, Vikunja seems to be working normally. I am trying to configure OIDC with Authelia as the provider. I have tried my best to follow the [configuration options](https://vikunja.io/docs/config-options#1-auth-openid) section of the documentation and this is the auth section of my configuration file:
```
auth:
  local:
    enabled: false
  openid:
    enabled: true
    providers:
      - authelia:
          name: Authelia
          authurl: https://auth.jacobmaiato.com
          clientid: "6a3fa2960c5936f0990746e0a0bc9cb577268692b0db7a99a2df0997a842cec1"
          clientsecret:
            file: /run/secrets/OIDC_CLIENT_SECRET
```
I have also tried to follow the OpenID [example configuration](https://vikunja.io/docs/openid-example-configurations#authelia) for Authelia (as a side note, the example seems to contradict the configuration options section of the docs):
```
auth:
  local:
    enabled: false
  openid:
    enabled: true
    providers:
      - name: Authelia
        authurl: https://auth.jacobmaiato.com
        clientid: "6a3fa2960c5936f0990746e0a0bc9cb577268692b0db7a99a2df0997a842cec1"
        clientsecret:
          file: /run/secrets/OIDC_CLIENT_SECRET
```
No matter how I try to set up the configuration, I get a similar go panic error every time I add anything to `providers`. Here are the logs when I try to load the page:
```
2024-12-09T02:08:05Z: INFO	▶ 001 Using config file: /etc/vikunja/config.yml
2024-12-09T02:08:05Z: INFO	▶ 002 Running migrations…
2024-12-09T02:08:06Z: INFO	▶ 06a Ran all migrations successfully.
2024-12-09T02:08:06Z: INFO	▶ 06c Vikunja version v0.24.5
⇨ http server started on [::]:3456
2024-12-09T02:08:09Z: WEB 	▶ 153.92.40.142  GET 200 /login 2.263307ms - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
2024-12-09T02:08:09Z: WEB 	▶ 153.92.40.142  GET 304 /assets/index-BdIWn3Ve.js 1.935422ms - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
2024-12-09T02:08:09Z: WEB 	▶ 153.92.40.142  GET 304 /assets/index-i4VRmjeA.css 2.377509ms - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
2024-12-09T02:08:09Z: - 	▶ echo recover.go:119 [PANIC RECOVER] interface conversion: interface {} is map[string]interface {}, not string goroutine 303 [running]:
code.vikunja.io/api/pkg/routes.NewEcho.Recover.RecoverWithConfig.func1.1.1()
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/recover.go:99 +0x156
panic({0x16a6740?, 0xc0005b25a0?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
code.vikunja.io/api/pkg/modules/auth/openid.getProviderFromMap(0xc000546360)
	/go/src/code.vikunja.io/api/pkg/modules/auth/openid/providers.go:137 +0x6e8
code.vikunja.io/api/pkg/modules/auth/openid.GetAllProviders()
	/go/src/code.vikunja.io/api/pkg/modules/auth/openid/providers.go:62 +0x2cd
code.vikunja.io/api/pkg/routes/api/v1.Info({0x3fe0b20, 0xc00050e000})
	/go/src/code.vikunja.io/api/pkg/routes/api/v1/info.go:118 +0x474
github.com/labstack/echo/v4.(*Echo).add.func1({0x3fe0b20, 0xc00050e000})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:587 +0x4b
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x3fe0b20, 0xc00050e000})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/cors.go:203 +0x463
code.vikunja.io/api/pkg/routes.setupStaticFrontendFilesHandler.static.func2.1({0x3fe0b20, 0xc00050e000})
	/go/src/code.vikunja.io/api/pkg/routes/static.go:144 +0x4c7
github.com/labstack/echo/v4/middleware.GzipWithConfig.func1.1({0x3fe0b20, 0xc00050e000})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/compress.go:90 +0x26f
code.vikunja.io/api/pkg/routes.NewEcho.Recover.RecoverWithConfig.func1.1({0x3fe0b20, 0xc00050e000})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/recover.go:130 +0x114
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x3fe0b20, 0xc00050e000})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/logger.go:125 +0xd8
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0003aa008, {0x3fb80d8, 0xc0001d0700}, 0xc0004b43c0)
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:674 +0x327
net/http.serverHandler.ServeHTTP({0xc0002c5c80?}, {0x3fb80d8?, 0xc0001d0700?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc0000b2090, {0x3fba718, 0xc0002c5b90})
	/usr/local/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 269
	/usr/local/go/src/net/http/server.go:3360 +0x485

goroutine 1 [chan receive]:
code.vikunja.io/api/pkg/cmd.init.func27(0xc00053a300?, {0x1859ffd?, 0x4?, 0x185a001?})
	/go/src/code.vikunja.io/api/pkg/cmd/web.go:98 +0x15d
github.com/spf13/cobra.(*Command).execute(0x4a45660, {0xc000132170, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x4a45660)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
code.vikunja.io/api/pkg/cmd.Execute()
	/go/src/code.vikunja.io/api/pkg/cmd/cmd.go:44 +0x1a
main.main()
	/go/src/code.vikunja.io/api/main.go:22 +0xf

goroutine 24 [select]:
database/sql.(*DB).connectionOpener(0xc0005336c0, {0x3fba750, 0xc00018ed20})
	/usr/local/go/src/database/sql/sql.go:1253 +0x87
created by database/sql.OpenDB in goroutine 1
	/usr/local/go/src/database/sql/sql.go:833 +0x130

goroutine 5 [select]:
database/sql.(*DB).connectionCleaner(0xc0005336c0, 0x0?)
	/usr/local/go/src/database/sql/sql.go:1096 +0x9c
created by database/sql.(*DB).startCleanerLocked in goroutine 1
	/usr/local/go/src/database/sql/sql.go:1083 +0x105

goroutine 33 [select]:
github.com/ThreeDotsLabs/watermill/pubsub/gochannel.(*GoChannel).Subscribe.func1(0xc0000c43c0, 0xc0001708f0)
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/pubsub/gochannel/pubsub.go:198 +0xad
created by github.com/ThreeDotsLabs/watermill/pubsub/gochannel.(*GoChannel).Subscribe in goroutine 8
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/pubsub/gochannel/pubsub.go:197 +0x446

goroutine 6 [select]:
code.vikunja.io/api/pkg/mail.StartMailDaemon.func1()
	/go/src/code.vikunja.io/api/pkg/mail/mail.go:107 +0xbb
created by code.vikunja.io/api/pkg/mail.StartMailDaemon in goroutine 1
	/go/src/code.vikunja.io/api/pkg/mail/mail.go:103 +0x196

goroutine 7 [select

2024-12-09T02:08:09Z: WEB 	▶ 153.92.40.142  GET 500 /api/v1/info 2.179443ms - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
2024-12-09T02:08:09Z: WEB 	▶ 153.92.40.142  GET 304 /manifest.webmanifest 689.984µs - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
2024-12-09T02:08:11Z: WEB 	▶ 153.92.40.142  GET 304 /sw.js 160.873µs - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
```

### Vikunja Version

0.24.5

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by maiatoja152** [comment]
I didn't realize file loading was only available in 0.25.0, thanks for the tip. However, I am still getting the same error using a string instead.
If I simplify the config down to this I get no errors (although of course this does not let me log in):
```
auth:
  local:
    enabled: false
  openid:
    enabled: true
    providers:
```
But as soon as I add anything to `providers` I get similar error messages about interface conversion (I don't know anything about Go to understand this). For example, this config:
```
auth:
  local:
    enabled: false
  openid:
    enabled: true
    providers:
      - authelia:
 ```
Creates this log:
```
2024-12-10T03:00:09Z: INFO	▶ 001 Using config file: /etc/vikunja/config.yml
2024-12-10T03:00:09Z: INFO	▶ 002 Running migrations…
2024-12-10T03:00:10Z: INFO	▶ 06a Ran all migrations successfully.
2024-12-10T03:00:10Z: INFO	▶ 06c Vikunja version v0.24.5
⇨ http server started on [::]:3456
2024-12-10T03:00:17Z: WEB 	▶ 37.19.212.50  GET 200 /login 1.366675ms - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
2024-12-10T03:00:17Z: WEB 	▶ 37.19.212.50  GET 304 /assets/index-BdIWn3Ve.js 24.334677ms - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
2024-12-10T03:00:17Z: WEB 	▶ 37.19.212.50  GET 304 /assets/index-i4VRmjeA.css 1.056791ms - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
2024-12-10T03:00:18Z: - 	▶ echo recover.go:119 [PANIC RECOVER] interface conversion: interface {} is nil, not string goroutine 308 [running]:
code.vikunja.io/api/pkg/routes.NewEcho.Recover.RecoverWithConfig.func1.1.1()
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/recover.go:99 +0x156
panic({0x16a6740?, 0xc00001c810?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
code.vikunja.io/api/pkg/modules/auth/openid.GetAllProviders()
	/go/src/code.vikunja.io/api/pkg/modules/auth/openid/providers.go:75 +0x6e8
code.vikunja.io/api/pkg/routes/api/v1.Info({0x3fe0b20, 0xc0000be0a0})
	/go/src/code.vikunja.io/api/pkg/routes/api/v1/info.go:118 +0x474
github.com/labstack/echo/v4.(*Echo).add.func1({0x3fe0b20, 0xc0000be0a0})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:587 +0x4b
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x3fe0b20, 0xc0000be0a0})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/cors.go:268 +0x87f
code.vikunja.io/api/pkg/routes.setupStaticFrontendFilesHandler.static.func2.1({0x3fe0b20, 0xc0000be0a0})
	/go/src/code.vikunja.io/api/pkg/routes/static.go:144 +0x4c7
github.com/labstack/echo/v4/middleware.GzipWithConfig.func1.1({0x3fe0b20, 0xc0000be0a0})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/compress.go:90 +0x26f
code.vikunja.io/api/pkg/routes.NewEcho.Recover.RecoverWithConfig.func1.1({0x3fe0b20, 0xc0000be0a0})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/recover.go:130 +0x114
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x3fe0b20, 0xc0000be0a0})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/logger.go:125 +0xd8
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0000d0008, {0x3fb80d8, 0xc0001d0620}, 0xc000292000)
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:674 +0x327
net/http.serverHandler.ServeHTTP({0xc00001c480?}, {0x3fb80d8?, 0xc0001d0620?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc0001a8ab0, {0x3fba718, 0xc0004921b0})
	/usr/local/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 32
	/usr/local/go/src/net/http/server.go:3360 +0x485

goroutine 1 [chan receive]:
code.vikunja.io/api/pkg/cmd.init.func27(0xc000000300?, {0x1859ffd?, 0x4?, 0x185a001?})
	/go/src/code.vikunja.io/api/pkg/cmd/web.go:98 +0x15d
github.com/spf13/cobra.(*Command).execute(0x4a45660, {0xc000150160, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x4a45660)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
code.vikunja.io/api/pkg/cmd.Execute()
	/go/src/code.vikunja.io/api/pkg/cmd/cmd.go:44 +0x1a
main.main()
	/go/src/code.vikunja.io/api/main.go:22 +0xf

goroutine 24 [select]:
database/sql.(*DB).connectionOpener(0xc00001aa90, {0x3fba750, 0xc000239900})
	/usr/local/go/src/database/sql/sql.go:1253 +0x87
created by database/sql.OpenDB in goroutine 1
	/usr/local/go/src/database/sql/sql.go:833 +0x130

goroutine 5 [select]:
database/sql.(*DB).connectionCleaner(0xc00001aa90, 0x0?)
	/usr/local/go/src/database/sql/sql.go:1096 +0x9c
created by database/sql.(*DB).startCleanerLocked in goroutine 1
	/usr/local/go/src/database/sql/sql.go:1083 +0x105

goroutine 28 [select]:
code.vikunja.io/api/pkg/mail.StartMailDaemon.func1()
	/go/src/code.vikunja.io/api/pkg/mail/mail.go:107 +0xbb
created by code.vikunja.io/api/pkg/mail.StartMailDaemon in goroutine 1
	/go/src/code.vikunja.io/api/pkg/mail/mail.go:103 +0x196

goroutine 6 [chan receive]:
github.com/ThreeDotsLabs/watermill/message.(*Router).Run(0xc0001d0540, {0x3fba210?, 0x4bd5540?})
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/router.go:378 +0x29f
code.vikunja.io/api/pkg/events.InitEvents()
	/go/src/code.vikunja.io/api/pkg/events/events.go:96 +0x3d3
code.vikunja.io/api/pkg/initialize.FullInit.func1()
	/go/src/code.vikunja.io/api/pkg/initialize/init.go:106 +0x19b
created by code.vikunja.io/api/pkg/initialize.FullInit in goroutine 1
	/go/src/code.vikunja.io/api/pkg/initialize/init.go:102 +0x77

goroutine 29 [select]:
github.com/

2024-12-10T03:00:18Z: WEB 	▶ 37.19.212.50  GET 500 /api/v1/info 2.676727ms - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
2024-12-10T03:00:18Z: WEB 	▶ 37.19.212.50  GET 304 /manifest.webmanifest 82.076µs - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
2024-12-10T03:00:19Z: WEB 	▶ 37.19.212.50  GET 304 /sw.js 157.953µs - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
```
And this config:
```
auth:
  local:
    enabled: false
  openid:
    enabled: true
    providers:
      - name: Authelia
```
Creates an almost identical log:
```
2024-12-10T03:03:46Z: INFO	▶ 001 Using config file: /etc/vikunja/config.yml
2024-12-10T03:03:46Z: INFO	▶ 002 Running migrations…
2024-12-10T03:03:46Z: INFO	▶ 06a Ran all migrations successfully.
2024-12-10T03:03:46Z: INFO	▶ 06c Vikunja version v0.24.5
⇨ http server started on [::]:3456
2024-12-10T03:03:51Z: WEB 	▶ 37.19.212.50  GET 200 /login 405.55µs - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
2024-12-10T03:03:51Z: WEB 	▶ 37.19.212.50  GET 304 /assets/index-BdIWn3Ve.js 11.531473ms - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
2024-12-10T03:03:51Z: WEB 	▶ 37.19.212.50  GET 304 /assets/index-i4VRmjeA.css 1.730383ms - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
2024-12-10T03:03:52Z: - 	▶ echo recover.go:119 [PANIC RECOVER] interface conversion: interface {} is nil, not string goroutine 223 [running]:
code.vikunja.io/api/pkg/routes.NewEcho.Recover.RecoverWithConfig.func1.1.1()
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/recover.go:99 +0x156
panic({0x16a6740?, 0xc000640690?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
code.vikunja.io/api/pkg/modules/auth/openid.getProviderFromMap(0xc0001b0300)
	/go/src/code.vikunja.io/api/pkg/modules/auth/openid/providers.go:135 +0x706
code.vikunja.io/api/pkg/modules/auth/openid.GetAllProviders()
	/go/src/code.vikunja.io/api/pkg/modules/auth/openid/providers.go:62 +0x2cd
code.vikunja.io/api/pkg/routes/api/v1.Info({0x3fe0b20, 0xc0001b4140})
	/go/src/code.vikunja.io/api/pkg/routes/api/v1/info.go:118 +0x474
github.com/labstack/echo/v4.(*Echo).add.func1({0x3fe0b20, 0xc0001b4140})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:587 +0x4b
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x3fe0b20, 0xc0001b4140})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/cors.go:268 +0x87f
code.vikunja.io/api/pkg/routes.setupStaticFrontendFilesHandler.static.func2.1({0x3fe0b20, 0xc0001b4140})
	/go/src/code.vikunja.io/api/pkg/routes/static.go:144 +0x4c7
github.com/labstack/echo/v4/middleware.GzipWithConfig.func1.1({0x3fe0b20, 0xc0001b4140})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/compress.go:90 +0x26f
code.vikunja.io/api/pkg/routes.NewEcho.Recover.RecoverWithConfig.func1.1({0x3fe0b20, 0xc0001b4140})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/recover.go:130 +0x114
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x3fe0b20, 0xc0001b4140})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/logger.go:125 +0xd8
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0003f7d48, {0x3fb80d8, 0xc0002ac2a0}, 0xc00039c280)
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:674 +0x327
net/http.serverHandler.ServeHTTP({0xc000640420?}, {0x3fb80d8?, 0xc0002ac2a0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc000280090, {0x3fba718, 0xc0004335f0})
	/usr/local/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 23
	/usr/local/go/src/net/http/server.go:3360 +0x485

goroutine 1 [chan receive]:
code.vikunja.io/api/pkg/cmd.init.func27(0xc000395b00?, {0x1859ffd?, 0x4?, 0x185a001?})
	/go/src/code.vikunja.io/api/pkg/cmd/web.go:98 +0x15d
github.com/spf13/cobra.(*Command).execute(0x4a45660, {0xc0000401d0, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x4a45660)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
code.vikunja.io/api/pkg/cmd.Execute()
	/go/src/code.vikunja.io/api/pkg/cmd/cmd.go:44 +0x1a
main.main()
	/go/src/code.vikunja.io/api/main.go:22 +0xf

goroutine 11 [select]:
database/sql.(*DB).connectionOpener(0xc0000d2820, {0x3fba750, 0xc0000fccd0})
	/usr/local/go/src/database/sql/sql.go:1253 +0x87
created by database/sql.OpenDB in goroutine 1
	/usr/local/go/src/database/sql/sql.go:833 +0x130

goroutine 37 [select]:
github.com/ThreeDotsLabs/watermill/pubsub/gochannel.(*GoChannel).Subscribe.func1(0xc000398370, 0xc0003ba000)
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/pubsub/gochannel/pubsub.go:198 +0xad
created by github.com/ThreeDotsLabs/watermill/pubsub/gochannel.(*GoChannel).Subscribe in goroutine 21
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/pubsub/gochannel/pubsub.go:197 +0x446

goroutine 38 [chan receive]:
github.com/ThreeDotsLabs/watermill/message.(*messageTransformSubscriberDecorator).Subscribe.func1()
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/decorator.go:52 +0x85
created by github.com/ThreeDotsLabs/watermill/message.(*messageTransformSubscriberDecorator).Subscribe in goroutine 21
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/decorator.go:51 +0xd0

goroutine 39 [chan receive]:
github.com/ThreeDotsLabs/watermill/message.(*messageTransformSubscribe

2024-12-10T03:03:52Z: WEB 	▶ 37.19.212.50  GET 500 /api/v1/info 15.216651ms - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
2024-12-10T03:03:52Z: WEB 	▶ 37.19.212.50  GET 304 /manifest.webmanifest 181.853µs - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
```
So it seems like I can't even begin to configure an OIDC provider. I have tried to add one line at a time and it's always the same error.

**Comment by maiatoja152** [comment]
Sorry, first time using github issues. I didn't mean to close it.

**Comment by kolaente** [comment]
> However, I am still getting the same error using a string instead.

Did you get the exact same traceroute?

**Comment by kolaente** [comment]
I've added a small change in 4512045cbfccbf872dfa8ab322aa62a86ccf5ca0 so that we'll at least get better error messages.

**Comment by maiatoja152** [comment]
> Did you get the exact same traceroute?

Ah, when checking it again I noticed the error was the same (`interface conversion: interface {} is nil, not string`) but it was on line 75 of `providers.go` instead of line 137. I looked at the code and got the hint I needed. Instead of using the `provider-key` syntax I used `name:` and now it's working. My working auth config:
```
auth:
  local:
    enabled: true
  openid:
    enabled: true
    providers:
      - name: Authelia
        authurl: https://auth.jacobmaiato.com
        clientid: "6a3fa2960c5936f0990746e0a0bc9cb577268692b0db7a99a2df0997a842cec1"
        clientsecret: "supersecret"
```
Looking at the latest version of `providers.go`, it seems like the syntax using `provider-key` will be supported in the next release? Or maybe I was doing it wrong.

**Comment by kolaente** [comment]
> Looking at the latest version of providers.go, it seems like the syntax using provider-key will be supported in the next release?

That's correct. The syntax will change with the next release.

**Comment by sailorbob134280** [comment]
Just to post here for awareness, this breaks the ability to configure OIDC client ID and secret using environment variables: https://community.vikunja.io/t/configure-openid-via-environment/628/18?u=sailorbob134280

**Comment by ameyp** [comment]
When can we expect the next release?

**Comment by kolaente** [comment]
@ameyp When it's done.

If you want to use it before then, [use an unstable build](https://vikunja.io/docs/versions/#unstable).
