### ISSUE TITLE
Internal server error on login attempt with invalid credentials when redis is configured

### ISSUE THREAD

**Issue by mmihalik** [go-vikunja/vikunja#377]
### Description

Hello,

I'm running a self hosted instance of vikunja with ~80 users and recently I have configured redis cache to help with vikunja performance. Ever since configuring redis, one of my users noticed that when login with an invalid password is attempted, Internal Server Error message appears on the login page. This is the stack trace from backend logs:

```
2024-12-13T16:29:36Z: - 	▶ echo recover.go:119 [PANIC RECOVER] interface conversion: interface {} is string, not int64 goroutine 14233 [running]:
code.vikunja.io/api/pkg/routes.NewEcho.Recover.RecoverWithConfig.func1.1.1()
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/recover.go:99 +0x156
panic({0x16a6740?, 0xc0004c4cc0?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
code.vikunja.io/api/pkg/user.handleFailedPassword(0xc0008402c0)
	/go/src/code.vikunja.io/api/pkg/user/user.go:378 +0x41c
code.vikunja.io/api/pkg/user.CheckUserCredentials(0xc000031c20?, 0xc0006bc100)
	/go/src/code.vikunja.io/api/pkg/user/user.go:353 +0xe6
code.vikunja.io/api/pkg/routes/api/v1.Login({0x3fe0b20, 0xc00048e140})
	/go/src/code.vikunja.io/api/pkg/routes/api/v1/login.go:56 +0xca
code.vikunja.io/api/pkg/routes.registerAPIRoutes.RateLimit.func32.1({0x3fe0b20, 0xc00048e140})
	/go/src/code.vikunja.io/api/pkg/routes/rate_limit.go:72 +0x69e
code.vikunja.io/api/pkg/routes.registerAPIRoutes.func1.1({0x3fe0b20, 0xc00048e140})
	/go/src/code.vikunja.io/api/pkg/routes/routes.go:231 +0x1a4
github.com/labstack/echo/v4.(*Echo).add.func1({0x3fe0b20, 0xc00048e140})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:587 +0x4b
code.vikunja.io/api/pkg/routes.setupStaticFrontendFilesHandler.static.func2.1({0x3fe0b20, 0xc00048e140})
	/go/src/code.vikunja.io/api/pkg/routes/static.go:144 +0x4c7
github.com/labstack/echo/v4/middleware.GzipWithConfig.func1.1({0x3fe0b20, 0xc00048e140})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/compress.go:90 +0x26f
code.vikunja.io/api/pkg/routes.NewEcho.Recover.RecoverWithConfig.func1.1({0x3fe0b20, 0xc00048e140})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/recover.go:130 +0x114
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x3fe0b20, 0xc00048e140})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/logger.go:125 +0xd8
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0004b2d88, {0x3fb80d8, 0xc000670000}, 0xc00025a640)
	/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:674 +0x327
net/http.serverHandler.ServeHTTP({0x3fb3b48?}, {0x3fb80d8?, 0xc000670000?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc00095ac60, {0x3fba718, 0xc0004de270})
	/usr/local/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 12
	/usr/local/go/src/net/http/server.go:3360 +0x485

goroutine 1 [chan receive, 869 minutes]:
code.vikunja.io/api/pkg/cmd.init.func27(0xc0000e7e00?, {0x1859ffd?, 0x4?, 0x185a001?})
	/go/src/code.vikunja.io/api/pkg/cmd/web.go:98 +0x15d
github.com/spf13/cobra.(*Command).execute(0x4a45660, {0xc0000401d0, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x4a45660)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
code.vikunja.io/api/pkg/cmd.Execute()
	/go/src/code.vikunja.io/api/pkg/cmd/cmd.go:44 +0x1a
main.main()
	/go/src/code.vikunja.io/api/main.go:22 +0xf

goroutine 26 [select, 869 minutes]:
database/sql.(*DB).connectionOpener(0xc000027860, {0x3fba750, 0xc000043ae0})
	/usr/local/go/src/database/sql/sql.go:1253 +0x87
created by database/sql.OpenDB in goroutine 1
	/usr/local/go/src/database/sql/sql.go:833 +0x130

goroutine 32 [select, 869 minutes]:
github.com/ThreeDotsLabs/watermill/pubsub/gochannel.(*GoChannel).Subscribe.func1(0xc00018c2d0, 0xc000244000)
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/pubsub/gochannel/pubsub.go:198 +0xad
created by github.com/ThreeDotsLabs/watermill/pubsub/gochannel.(*GoChannel).Subscribe in goroutine 10
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/pubsub/gochannel/pubsub.go:197 +0x446

goroutine 8 [select]:
code.vikunja.io/api/pkg/mail.StartMailDaemon.func1()
	/go/src/code.vikunja.io/api/pkg/mail/mail.go:107 +0xbb
created by code.vikunja.io/api/pkg/mail.StartMailDaemon in goroutine 1
	/go/src/code.vikunja.io/api/pkg/mail/mail.go:103 +0x196

goroutine 9 [select]:
github.com/robfig/cron/v3.(*Cron).run(0xc000030f00)
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.g
```

I also created a minimal setup that can be used to reproduce the issue, just try logging in with user `user` using a random password.

[invalid-credentials-redis-error.zip](https://github.com/user-attachments/files/18129554/invalid-credentials-redis-error.zip)

Would be nice if you could fix this.

### Vikunja Version

0.24.5

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
Fixed in 28a58303f02acc11e801a1ef5a85c3615c9b7b56, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
