### ISSUE TITLE
Trello import fails with "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by martinhaintz** [go-vikunja/vikunja#378]
### Description

I tried importing the Trello boards into vikunja, but it failed. I looked through other issues and the forum but couldn't resolve this.

Do you have any ideas about what is causing the issue?

Thanks.

Here is the log:

```
2024-12-14T12:52:13Z: DEBUG	▶ 7502 [Trello Migration] Downloaded card attachment xxxxxxxxxxx
2024-12-14T12:52:13Z: DEBUG	▶ 7503 [Trello Migration] Downloading card attachment xxxxxxxxxxx
2024-12-14T12:52:13Z: DEBUG	▶ 7504 [Trello Migration] Downloaded card attachment xxxxxxxxxxx
2024-12-14T12:52:13Z: DEBUG	▶ 7505 [Trello Migration] Downloading card attachment xxxxxxxxxxx
2024-12-14T12:52:14Z: DEBUG	▶ 7506 [Trello Migration] Downloaded card attachment xxxxxxxxxxx
2024-12-14T12:52:14Z: DEBUG	▶ 7507 [Trello Migration] Downloading card attachment xxxxxxxxxxx
2024-12-14T12:52:14Z: DEBUG	▶ 7508 [Trello Migration] Downloaded card attachment xxxxxxxxxxx
2024-12-14T12:52:14Z: ERROR	▶ 750f Error while handling message xxxxxxxxxxx, subscriber_poisoned=gochannel.GoChannel, reason_poisoned=panic occurred: "invalid memory address or nil pointer dereference", stacktrace:
goroutine 403 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:26 +0x5e
github.com/ThreeDotsLabs/watermill/message/router/middleware.Recoverer.func1.1()
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/router/middleware/recoverer.go:29 +0x50
panic({0x1696420?, 0x4a1d7a0?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
code.vikunja.io/api/pkg/modules/migration/trello.convertTrelloDataToVikunja({0xc0274c6ef0, 0xe}, {0xc007159580, 0xb, 0x2?}, {0xc027337180, 0x4c}, 0xc006c89860)
	/go/src/code.vikunja.io/api/pkg/modules/migration/trello/trello.go:411 +0x1f2b
code.vikunja.io/api/pkg/modules/migration/trello.(*Migration).Migrate(0xc000040ba0, 0xc006f186e0)
	/go/src/code.vikunja.io/api/pkg/modules/migration/trello/trello.go:492 +0xa53
code.vikunja.io/api/pkg/modules/migration/handler.migrateInListener({0x3fb7718, 0xc000040ba0}, 0xc0011b4ab0)
	/go/src/code.vikunja.io/api/pkg/modules/migration/handler/listeners.go:115 +0x19d
code.vikunja.io/api/pkg/modules/migration/handler.(*MigrationListener).Handle(0x3e04d38?, 0xc00097fb60)
	/go/src/code.vikunja.io/api/pkg/modules/migration/handler/listeners.go:75 +0x172
github.com/ThreeDotsLabs/watermill/message.(*Router).AddNoPublisherHandler.func1(0xc000dacf50?)
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/router.go:338 +0x17
github.com/ThreeDotsLabs/watermill/message/router/middleware.Recoverer.func1(0xc000975d50?)
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/router/middleware/recoverer.go:33 +0x70
github.com/ThreeDotsLabs/watermill/message/router/middleware.Retry.Middleware-fm.Retry.Middleware.func1(0xc00097fb60)
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/router/middleware/retry.go:72 +0x27e
github.com/ThreeDotsLabs/watermill/message/router/middleware.poisonQueue.Middleware-fm.poisonQueue.Middleware.func1(0x16b2a40?)
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/router/middleware/poison.go:99 +0xa2
github.com/ThreeDotsLabs/watermill/components/metrics.HandlerPrometheusMetricsMiddleware.Middleware-fm.HandlerPrometheusMetricsMiddleware.Middleware.func1(0xc00097fb60)
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/components/metrics/handler.go:58 +0x19b
github.com/ThreeDotsLabs/watermill/message.(*handler).handleMessage(0xc000518270, 0xc00097fb60, 0xc0003a8618)
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/router.go:783 +0x15b
created by github.com/ThreeDotsLabs/watermill/message.(*handler).run in goroutine 283
	/go/pkg/mod/github.com/!three!dots!labs/watermill@v1.3.7/message/router.go:628 +0x2a5
, topic_poisoned=migration.requested, handler_poisoned=migration.requested.migration.listener,  payload={"migrator":{"code":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"},"user":{"id":1,"name":"IT Admin","username":"admin","email":"admin@xxxxxxxxxxx.com","created":"0001-01-01T00:00:00Z","updated":"0001-01-01T00:00:00Z"},"migrator_kind":"trello"}
2024-12-14T12:53:00Z: DEBUG	▶ 7512 [Task Reminder Cron] Looking for reminders between 2024-12-14 13:53:00 +0100 CET and 2024-12-14 13:54:00 +0100 CET to send...
2024-12-14T12:53:00Z: DEBUG	▶ 7516 [Task Reminder Cron] Found 0 reminders
2024-12-14T12:53:00Z: DEBUG	▶ 7518 [Undone Overdue Tasks Reminder] Sending reminders to 0 users
2024-12-14T12:54:00Z: DEBUG	▶ 751a [Task Reminder Cron] Looking for reminders between 2024-12-14 13:54:00 +0100 CET and 2024-12-14 13:55:00 +0100 CET to send...
2024-12-14T12:54:00Z: DEBUG	▶ 7
```

Here is my docker-compose:
```
name: vikunja
services:
  cft-vikunja-xxxxxxxxxx-com:
    container_name: cft-vikunja-xxxxxxxxxx-com
    image: cloudflare/cloudflared:2024.11.1
    restart: always
    environment:
      TUNNEL_TOKEN: $TUNNEL_TOKEN
    command: tunnel --no-autoupdate run
    networks:
      - cft-vikunja-xxxxxxxxxx-com

  vikunja:
    image: vikunja/vikunja:0.24.5
    container_name: vikunja
    environment:
      VIKUNJA_SERVICE_JWTSECRET: $VIKUNJA_SERVICE_JWTSECRET
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.xxxxxxxxxx.com
      #VIKUNJA_SERVICE_ROOTPATH: /app/vikunja/config
      VIKUNJA_SERVICE_ENABLEREGISTRATION: false
      VIKUNJA_SERVICE_TIMEZONE: Europe/Vienna
      VIKUNJA_SERVICE_ENABLEPUBLICTEAMS: false
      VIKUNJA_SERVICE_ENABLEOPENIDTEAMUSERSEARCH: true
      VIKUNJA_DATABASE_HOST: vikunja-db
      VIKUNJA_DATABASE_PASSWORD: $VIKUNJA_DATABASE_PASSWORD
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_REDIS_ENABLED: 1
      VIKUNJA_REDIS_HOST: 'vikunja-redis:6379'
      VIKUNJA_CACHE_ENABLED: 1
      VIKUNJA_CACHE_TYPE: redis
      VIKUNJA_MAILER_ENABLED: true
      VIKUNJA_MAILER_HOST: smtp.gmail.com
      VIKUNJA_MAILER_PORT: 465
      VIKUNJA_MAILER_AUTHTYPE: plain
      VIKUNJA_MAILER_USERNAME: it-services@xxxxxxxxxx.com
      VIKUNJA_MAILER_PASSWORD: $VIKUNJA_MAILER_PASSWORD
      VIKUNJA_MAILER_FROMEMAIL: "it-services @ vikunja"
      VIKUNJA_MIGRATION_TRELLO_ENABLE: true
      VIKUNJA_MIGRATION_TRELLO_KEY: $VIKUNJA_MIGRATION_TRELLO_KEY
      VIKUNJA_BACKGROUNDS_PROVIDERS_UNSPLASH_ENABLED: true
      VIKUNJA_BACKGROUNDS_PROVIDERS_UNSPLASH_ACCESSTOKEN: $VIKUNJA_UNSPLASH_ACCESSTOKEN
      VIKUNJA_KEYVALUE_TYPE: redis
      VIKUNJA_AUTH_LOCAL_ENABLED: false
      VIKUNJA_DEFAULTSETTINGS_EMAIL_REMINDERS_ENABLED: true
      VIKUNJA_DEFAULTSETTINGS_DISCOVERABLE_BY_NAME: true
      VIKUNJA_DEFAULTSETTINGS_DISCOVERABLE_BY_EMAIL: true
      VIKUNJA_DEFAULTSETTINGS_OVERDUE_TASKS_REMINDERS_ENABLED: true
      VIKUNJA_DEFAULTSETTINGS_OVERDUE_TASKS_REMINDERS_TIME: "7:00"
      VIKUNJA_DEFAULTSETTINGS_DEFAULT_PROJECT_ID: 0
      VIKUNJA_DEFAULTSETTINGS_WEEK_START: 1
      VIKUNJA_DEFAULTSETTINGS_TIMEZONE: Europe/Vienna
      VIKUNJA_LOG_LEVEL: DEBUG
    volumes:
      - vikunja-files:/app/vikunja/files
      - vikunja-config:/etc/vikunja
    depends_on:
      - vikunja-db
      - vikunja-redis
    restart: always
    networks:
      - vikunja
      - cft-vikunja-xxxxxxxxxx-com

  vikunja-db:
    image: postgres:16.6
    container_name: vikunja-db
    environment:
      POSTGRES_DB: vikunja
      POSTGRES_USER: vikunja
      POSTGRES_PASSWORD: $VIKUNJA_DATABASE_PASSWORD
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 2s    
    networks:
      - vikunja

  vikunja-redis:
    image: redis:7.4.1
    container_name: vikunja-redis
    networks:
      - vikunja

volumes:
  pg-data:
  vikunja-files:
  vikunja-config:

networks:
  vikunja:
    name: vikunja
  cft-vikunja-xxxxxxxxxx-com:
    name: cft-vikunja-xxxxxxxxxx-com

```

### Vikunja Version

0.24.5

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

![image](https://github.com/user-attachments/assets/cb5befcf-0b04-473a-933e-78afcb9aea5b)

**Comment by kolaente** [comment]
Fixed in 47ff7d8ad3b33591f23bc0d67026368b70b7fc6d, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).

**Comment by kolaente** [comment]
The error indicates that your file storage does not work ("permission denied").

**Comment by martinhaintz** [comment]
This is interesting. All my other docker volumes are working. How is it possible that only this docker volume does not work? 

Is there anything I missed?

**Comment by kolaente** [comment]
Vikunja does not change the permissions in the volume by itself. You need to do this manually: https://vikunja.io/docs/docker-walkthrough#ensure-adequate-file-permissions
